// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnePieceCardManagement.Models;

[Keyless]
public partial class TattoosByPosition
{
    [Column("position")]
    [StringLength(100)]
    public string Position { get; set; }

    [Column("count")]
    public long? Count { get; set; }

    [Column("avg_price")]
    public decimal? AvgPrice { get; set; }

    [Column("avg_rating")]
    public decimal? AvgRating { get; set; }
}