// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnePieceCardManagement.Models;

[Table("tattoos")]
[Index("Position", Name = "idx_tattoos_position")]
[Index("AveragePrice", Name = "idx_tattoos_price")]
[Index("Rating", Name = "idx_tattoos_rating")]
[Index("Style", Name = "idx_tattoos_style")]
public partial class Tattoos
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("image_url")]
    [StringLength(500)]
    public string ImageUrl { get; set; }

    [Required]
    [Column("position")]
    [StringLength(100)]
    public string Position { get; set; }

    [Required]
    [Column("style")]
    [StringLength(100)]
    public string Style { get; set; }

    [Column("average_price")]
    [Precision(10, 2)]
    public decimal AveragePrice { get; set; }

    [Column("notes")]
    public string Notes { get; set; }

    [Column("rating")]
    public int Rating { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }
}