// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnePieceCardManagement.Models;

[Keyless]
public partial class TattooStatistics
{
    [Column("total_tattoos")]
    public long? TotalTattoos { get; set; }

    [Column("avg_price")]
    public decimal? AvgPrice { get; set; }

    [Column("min_price")]
    public decimal? MinPrice { get; set; }

    [Column("max_price")]
    public decimal? MaxPrice { get; set; }

    [Column("avg_rating")]
    public decimal? AvgRating { get; set; }
}