// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnePieceCardManagement.Models;

[Table("tattoo_positions")]
[Index("Name", Name = "tattoo_positions_name_key", IsUnique = true)]
public partial class TattooPositions
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Column("body_area")]
    [StringLength(50)]
    public string BodyArea { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }
}