name: Build and Deploy .NET API to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish project
      run: dotnet publish OnePieceCardManagement/OnePieceCardManagement.csproj -c Release -r linux-arm64 --self-contained -o ./OnePieceCardManagement/publish

    - name: Copy published files to Raspberry Pi
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.RPI_HOST }}
        username: ${{ secrets.RPI_USER }}
        key: ${{ secrets.RPI_SSH_KEY }}
        source: "OnePieceCardManagement/publish/*"
        target: "/home/maton/opcm-be"

    - name: Restart Raspberry Pi API service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RPI_HOST }}
        username: ${{ secrets.RPI_USER }}
        key: ${{ secrets.RPI_SSH_KEY }}
        script: |
          sudo systemctl restart onepiececardmanagement.service
